### PR TITLE
Cut the deck

### PR DESCRIPTION
**Pull request by darrencauthon**
Cutting a deck may seem irrelevant when the cards are randomized by a computer, but... hey, if you ask the dealer to cut the cards, he/she **has to cut the cards.** The deck is meant to represent an actual deck of cards, so... why not? :smile:

### CODE REVIEW

**Comment by jdan** [comment]
Haha I love it! Thanks. You're awesome for including tests with these.

Any interest in working on this library as a collaborator?

**Comment by jdan** [comment]
You can keep sending PRs (they're very nice!) but if you want some more freedom and feel you can manage other issues/PRs in the future let me know :)

**Comment by darrencauthon** [comment]
Thanks!  Being a collaborator would be fine, I'd be happy to help.

**Comment by jdan** [comment]
Added! Feel free to edit the README and gemspec with your info. Also, send over your rubygems account so I can add you as an owner to this gem (you'll be able to push out new releases).

Looking forward to working with you, no pressure ;)

Also I should probably extend this offer to @joeletizia and @xtagon

**Comment by darrencauthon** [comment]
@jdan Sure, my rubygems profile is:  https://rubygems.org/profiles/darrencauthon

**Comment by jdan** [comment]
Done :rainbow:

**Comment by joeletizia** [comment]
Ha. blast from the past. Totally forgot about this. Yeah, put me down. 

Crazy how much my tests suck. Maybe when my gf is away this weekend I'll clean them up.

@jdan grats on KhanAcademy btw. 

https://rubygems.org/profiles/joeletizia

**Comment by jdan** [comment]
@joeletizia Thanks :) Blast from the past indeed, I posted it to r/ruby the other day and it picked up a little momentum

Added!

**Pull request merged**
