### PR TITLE
Gem spec setup and testing framework.

### PR DESCRIPTION
**Pull request by joeletizia**
Cool idea. Cool if I help?

### CODE REVIEW

**Comment by jdan** [comment]
Oh wow, excellent. Some questions.
- Do we need to add a rake task for testing? `rake test` or something.
- Should I put my name under `LICENSE`?

**Comment by joeletizia** [comment]
Definitely change the gem spec to include your info. 

For testing I was just running rspec manually. This is my first time bundling a gem too, so I'm interested in best practice as well.

**Comment by xtagon** [comment]
Nothing wrong with running rspec manually, but if you want a Rake task here's how I did it in one of my gems: [Rakefile](https://github.com/xtagon/scoreoid-gem/blob/a24cc7592c5ace6948f38adfe2072663bf44d3c4/Rakefile)

Lines 2 and 5 give you the Rspec task. Run `rake -T` to see it listed.
Line 8 runs it as the default action, which I find handy.

**Comment by joeletizia** [comment]
You can now run the tests with either  `rake` or `rake spec`

**Comment by joeletizia** [comment]
You should also:
- [x] add your email to the gemspec

**Comment by jdan** [comment]
https://rubygems.org/gems/rubycards

:clap:

How do "owners" work? Is it appropriate to have more than one?

On another note, I'm wondering if we should throw all the classes into a Rubycards module.

```
h = Rubycards::Hand.new
```

Doesn't seem to cool, though...

**Comment by xtagon** [comment]
Throwing your classes into a module would be good, actually. This help prevent potentially clashing names when someone uses your library in an app. Anyone who wants to can simply `include Rubycards` if they don't want to keep typing the module name.

**Comment by joeletizia** [comment]
I agree. Module it.

**Pull request merged**
