### PR TITLE
Add a rake task for IRB console

### PR DESCRIPTION
**Pull request by xtagon**

### CODE REVIEW

**Comment by jdan** [comment]
Looks good, thanks! Should I add something to the README?

**Comment by xtagon** [comment]
> Should I add something to the README?

Nah, it's mainly for developers. This way you can play with an IRB session that loads your current development version instead of it loading whatever gem release of your project happens to be installed.

**Comment by jdan** [comment]
Alright, thanks for adding this. Learning a ton from you.

## 

jordan scales
scalesjordan@gmail.com
http://jordanscales.com

**Comment by xtagon** [comment]
No problem :)
Hacking is caring.

**Pull request merged**
